### ISSUE TITLE
Can I ask for individual demand

### ISSUE THREAD

**Issue by cftyujmnbvgh** [guilherme-gm/KirieZ_DoraemonSoSMods#7]
Hi, I play this game for this year, and I love your mod, it's helpful
If ok, can you do a mod for Nobita house desk or bookcase can read ledger and signboard and illustrated book?
I know doing this mod need take your time, it's OK if you don't want do this

My mother tongue is not English, so please forgive me if I speak badly

**Comment by guilherme-gm** [comment]
Hello,
Happy to know you are enjoying them :D

I like this idea! I will try to check what I can do during the weekend and update here

**Comment by guilherme-gm** [comment]
I managed to get this working 😄 
I have to put some finishing touches and should be released in a few days

**Comment by guilherme-gm** [comment]
Hey, I have just released EasyBoards v1.0.0, I believe it includes all menus you wanted to see.

You can get it here:
- Latest release in the repository: https://github.com/guilherme-gm/KirieZ_DoraemonSoSMods/releases
- Nexus: https://www.nexusmods.com/doraemonstoryofseasons/mods/4

Let me know if I forgot something or you find any issues!

**Comment by cftyujmnbvgh** [comment]
This is really awesome, it makes the game a lot more comfortable to play
sincere gratitude
